Wrap DontFragment assignment in a catch for OSX
ela-compil/BACnet pull request #116
Opened 2022-10-31 09:08 UTC by YarekTyshchenko

https://github.com/dotnet/runtime/issues/27653

Fixes #115

2022-11-19 12:38 UTC, gralin requested changes

2022-11-21 09:09 UTC, YarekTyshchenko commented on Transport/BacnetIpUdpProtocolTransport.cs
> +        try
Good thinking. In this case the Warning might have a useful stacktrace, so I think I'll include it into the log

2022-11-21 10:18 UTC, gralin approved these changes

2022-11-21 10:19 UTC, merged

2022-11-21 10:19 UTC, gralin commented
Thanks @YarekTyshchenko