Added time from method overload for read by range
ela-compil/BACnet pull request #69
Opened 2021-02-22 08:08 UTC by patrickthoma

2021-02-24 22:58 UTC, gralin requested changes
Thank you @patrickthoma for your pull request! 🔥  Indeed the original implementation was limited (as it's the case no only here). I just suggested some cosmetic changed, hope you don't mind.

2021-02-24 22:58 UTC, gralin commented on BACnetClient.cs
> +            using (var result = getResult())
Just a suggestion to make the code shorter

```csharp
Func<IAsyncResult> getResult;
...
getResult = () => BeginReadRangeRequest(adr, objectId, readFrom, quantityCopy, true, invokeId);
getResult = () => BeginReadRangeRequest(adr, objectId, idxBegin, quantityCopy, true, invokeId);
...
using (var result = getResult() as BacnetAsyncResult)
```

2021-02-24 22:58 UTC, gralin commented on BACnetClient.cs
> +
Please remove blank line

2021-02-25 09:36 UTC, patrickthoma commented
Thank you very much for your input and your explanations, I changed the code accordingly.

2021-02-25 20:33 UTC, gralin approved these changes
Thanks!

2021-02-25 20:33 UTC, merged